### ISSUE TITLE
Option to adjust the borderradius

### ISSUE THREAD

**Issue by shayant98** [smocken78/DatePickerTimetable#2]
Hi can we have the ability to modify the border radius or the whole container to match the application style.

**Comment by smocken78** [comment]
Hi, 
i suggest to add an optional borderRadius parameter to the constructor, otherwise the required selectionColor could be confusing.
If you have a better idea, just let me know, else i would implement it next week.

**Comment by smocken78** [comment]
Just uploaded:
date_picker_timetable: ^0.0.5
to pub.dev.

You can now modify borderRadius using paramter borderRadius
